TOPLEVEL = dpram

PWD=$(shell pwd)
COCOTB=~/2014_devel/EDA/cocotb

VERILOG_SOURCES = $(PWD)/../../hdl/dpram.v
MODULE=test_dpram #cocotb,test_discovery,test_external,test_regression

include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim